csmserver/views/custom_command.py
# =============================================================================
# Copyright (c) 2016, Cisco Systems, Inc
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.
# =============================================================================
from flask import Blueprint
from flask import jsonify
from flask import render_template
from flask import request
from flask import redirect
from flask import url_for
from flask import abort
from flask import send_file
from flask import flash
from flask_login import login_required
from flask_login import current_user

from database import DBSession

from models import logger
from models import CustomCommandProfile

from constants import get_temp_directory

from wtforms import Form
from wtforms import StringField
from wtforms import TextAreaField
from wtforms.validators import Length, required

from utils import create_temp_user_directory
from utils import create_directory
from utils import make_file_writable

from common import create_or_update_custom_command_profile
from common import delete_custom_command_profile
from common import get_custom_command_profile
from common import can_delete

import os
import json

custom_command = Blueprint('custom_command', __name__, url_prefix='/custom_command_profiles')


@custom_command.route('/', methods=['GET', 'POST'])
@login_required
def home():
    msg = ''
    # Custom Command Profile import
    if request.method == 'POST':
        file = request.files['file']
        if file:
            if not allowed_file(file.filename):
                msg = "Incorrect file format -- " + file.filename + " must be .json"
            else:
                file_path = os.path.join(get_temp_directory(), "custom_command_profiles.json")
                file.save(file_path)
                failed = ""

                with open(file_path, 'r') as f:
                    try:
                        s = json.load(f)
                    except:
                        msg = "Incorrect file format -- " + file.filename + " must be a valid JSON file."
                        flash(msg, 'import_feedback')
                        return redirect(url_for(".home"))

                    if "CSM Server:Custom Command Profile" not in s.keys():
                        msg = file.filename + " is not in the correct Custom Command Profile format."
                    else:
                        db_session = DBSession
                        custom_profiles = [p for (p,) in DBSession().query(CustomCommandProfile.profile_name).all()]
                        d = s["CSM Server:Custom Command Profile"]

                        for profile_name in d.keys():
                            name = ''
                            if profile_name in custom_profiles:
                                name = profile_name
                                # Will keep appending ' - copy' until it hits a unique name
                                while name in custom_profiles:
                                    name += " - copy"
                                msg += profile_name + ' -> ' + name + '\n'
                                custom_profiles.append(name)

                            if len(name) < 100 and len(profile_name) < 100:
                                try:
                                    profile = CustomCommandProfile(
                                        profile_name=name if name else profile_name,
                                        command_list=d[profile_name],
                                        created_by=current_user.username
                                    )
                                    db_session.add(profile)
                                    db_session.commit()
                                except:
                                    failed += profile_name + '\n'
                            else:
                                failed += profile_name + ' (name too long)\n'

                        if msg:
                            msg = "The following profiles already exist and will try to be imported under modified names:\n\n" + \
                                msg + '\n'
                            if failed:
                                msg += 'The following profiles failed to import:\n\n' + failed
                        elif failed:
                            msg = 'The following profiles failed to import:\n\n' + failed
                        else:
                            msg = "Custom Command Profile import was successful!"

                # delete file
                os.remove(file_path)

            flash(msg, 'import_feedback')
            return redirect(url_for(".home"))

    custom_command_profile_form = CustomCommandProfileForm(request.form)
    return render_template('custom_command/custom_command_profile.html',
                           form=custom_command_profile_form)


@custom_command.route('/api/get_command_profiles')
@login_required
def api_get_command_profiles():
    custom_profiles = DBSession().query(CustomCommandProfile).filter().all()

    rows = []
    for profile in custom_profiles:
        row = {'id': profile.id,
               'profile_name': profile.profile_name,
               'command_list': profile.command_list,
               'created_by': profile.created_by}

        rows.append(row)

    return jsonify(**{'data': rows})


@custom_command.route('/command_profile/create', methods=['GET', 'POST'])
@login_required
def command_profile_create():
    db_session = DBSession()

    form = CustomCommandProfileForm(request.form)

    if request.method == 'POST' and form.validate():
        command_profile = get_custom_command_profile(db_session, form.profile_name.data)

        if command_profile is not None:
            return render_template('custom_command/command_profile_edit.html',
                                   form=form, duplicate_error=True)

        create_or_update_custom_command_profile(
            db_session=db_session,
            profile_name=form.profile_name.data,
            command_list=','.join([l for l in form.command_list.data.splitlines() if l]),
            created_by=current_user.username
        )

        return redirect(url_for('custom_command.home'))
    else:

        return render_template('custom_command/command_profile_edit.html', form=form)


@custom_command.route('/command_profile/<profile_name>/edit', methods=['GET', 'POST'])
@login_required
def command_profile_edit(profile_name):
    db_session = DBSession()

    command_profile = get_custom_command_profile(db_session, profile_name)
    if command_profile is None:
        abort(404)

    form = CustomCommandProfileForm(request.form)

    if request.method == 'POST' and form.validate():
        if profile_name != form.profile_name.data and \
                        get_custom_command_profile(db_session, form.profile_name.data) is not None:
            return render_template('custom_command/command_profile_edit.html',
                                   form=form, duplicate_error=True)

        create_or_update_custom_command_profile(
            db_session=db_session,
            profile_name=form.profile_name.data,
            command_list=','.join([l for l in form.command_list.data.splitlines() if l]),
            created_by=current_user.username,
            custom_command_profile=get_custom_command_profile(db_session, profile_name)
        )

        return redirect(url_for('custom_command.home'))
    else:
        form.profile_name.data = command_profile.profile_name
        if command_profile.command_list is not None:
            form.command_list.data = '\n'.join(command_profile.command_list.split(','))

    return render_template('custom_command/command_profile_edit.html', form=form)


@custom_command.route('/command_profile/<profile_name>/delete', methods=['DELETE'])
@login_required
def custom_command_profile_delete(profile_name):
    if not can_delete(current_user):
        abort(401)

    db_session = DBSession()

    try:
        delete_custom_command_profile(db_session, profile_name)
        return jsonify({'status': 'OK'})
    except Exception as e:
        logger.exception('custom_command_profile_delete hit exception.')
        return jsonify({'status': e.message})


@custom_command.route('/export_command_profiles', methods=['POST'])
@login_required
def export_command_profiles():
    db_session = DBSession()
    profiles_list = request.args.getlist('profiles_list[]')[0].split(",")
    db_profiles = db_session.query(CustomCommandProfile).all()
    d = {"CSM Server:Custom Command Profile": {}}

    for profile in db_profiles:
        if profile.profile_name in profiles_list:

csmserver/templates/custom_command/command_profile_edit.html
{% extends 'base_software.html' %}

{% from 'host/common.html' import edit_field %}
{% from 'host/common.html' import alert_duplicate %}

{% if request.endpoint.endswith('edit') %}
    {% set isEdit = True %}
{% else %}
    {% set isEdit = False %}
{% endif %}

{% block head %}

<script>
    $(function() {
        var spinner = $('#spinner');
        spinner.hide();

        $('#command_list').attr("wrap", "off");

        $('#form').submit(function() {
            var current_form = this;
            var profile_name = $('#profile_name').val();
            var acceptable_string = get_acceptable_string(profile_name.trim());
            $('#command_list').val(trim_lines($('#command_list').val()));

            if (acceptable_string != profile_name) {
                var message = get_acceptable_string_message('Profile name', profile_name, acceptable_string);
                bootbox.confirm(message, function(result) {
                    if (result) {
                        $('#profile_name').val(acceptable_string);
                    }
                });
            } else {
                return true;
            }

            return false;
        });
    });
</script>
  
<style>
    .modal-dialog {    
        width: 850px;
    }
    a:link, a:visited {
        text-decoration:none;
    }
    th,
    td {
        white-space: nowrap;
    }
</style>
  
{% endblock %}

{% block main %}

<div class="row">
    <div class="well col-sm-offset-2 col-sm-8">
        <form id="form" method=post class="form-horizontal">
            <legend>{% if isEdit %}Edit Command Profile{% else %}Create Command Profile{% endif %}</legend>
            
            {{ alert_duplicate(form.profile_name.data, duplicate_error) }}
            {{ edit_field(form.profile_name, class="form-control") }}
            {{ edit_field(form.command_list, class="form-control", spellcheck="false", rows="10") }}
            
            <div class="form-actions">
                <div class="btn col-sm-offset-5">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="button" onClick="location.href='{{ url_for('custom_command.home') }}'" class="btn btn-default">Cancel</button>
                    <img id="spinner" src="{{ url_for('static', filename='spinner.gif') }}">
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

csmserver/templates/custom_command/custom_command_profile.html
{% extends 'base_software.html' %}
{% from 'host/common.html' import edit_field %}

{% block head %}
  
<script charset="utf-8">

    $(function() {

        var msg = $('#import-form').data("msg");
        if( msg != '' ){
            bootbox.alert(msg);
        }

        $('a[href="#profiles-tab"]').tab('show');

        var profile_id = $.cookie('profile-id');

        // Use delegate pattern for event
        $("#profile-table").on("click", ".data-delete-link", function() {
            var delete_url = $(this).attr('data-delete-url');
            var profile_name = $(this).attr('data-delete-profile-name');

            bootbox.confirm("You are about to delete custom command profile \'" + profile_name + "\'.  OK to proceed?", function(result) {
                if (result) {
                    $.ajax({
                        url: delete_url,
                        type: 'DELETE',
                        success: function(result) {
                            if (result.status == 'OK') {
                                profile_table.api().ajax.reload();
                            } else {
                                bootbox.alert('Delete failed.');
                            }
                        }
                    });
                }
            });
        });
        var profile_table = $("#profile-table").dataTable({
            "order": [
                [0, "asc"]
            ],
            "columnDefs": [{
                "targets": 0,
                "data": 'profile_name',
                "render": function(data, type, row) {
                    return '<a href="/custom_command_profiles/command_profile/' + data + '/edit">' + data + '</a>';
                }
            }, {
                "targets": 1,
                "data": 'command_list',
                "render": function(data, type, row) {
                    return insert_slider(comma2br(data), row['id']);
                }
            },{
                "targets": 2,
                "data": 'created_by',
            }, {
                "targets": 3,
                "data": 'profile_name',
                "render": function(data, type, row) {
                    return '<a class="data-delete-link" href="javascript://"  \
                data-delete-profile-name="' + data + '" \
                data-delete-url="/custom_command_profiles/command_profile/' + data + '/delete">Delete</a>';
                }
            }],
            "ajax": {
                "url": "{{ url_for('custom_command.api_get_command_profiles') }}",
            }
        });

        function insert_slider(command_list, id) {
            if (command_list != null && command_list.length > 0) {
                var html = '<a href="javascript://" data-toggle="collapse" data-target="#toggle' + id + '">' +
                    '<center><img src=\"{{ url_for('static', filename='file_open.png') }}\"></center>' +
                    '</a>' +
                    '<!-- Collapsible Element HTML -->' +
                    '<div id="toggle' + id + '" class="collapse">' +
                    '<div style="white-space: nowrap;">' +command_list.replace(/,/g, "<br/>") +
                    '</div>' +
                    '</div>';
                return html;
            } else {
                return '&nbsp;';
            }
        }

        var export_profiles_table = $('#export-profiles-datatable').dataTable({
            "order": [
                [1, "asc"]
            ],
            "pageLength": 100,
            "scrollY": 250,
            "columnDefs": [{
                "sortable": false,
                "targets": 0,
                "data": 'profile_name',
                "render": function ( data, type, row ) {
                    return '<center><input type="checkbox" value="' + data + '" class="check" name="profile_names"></center>';
                }
            }, {
                "sortable": true,
                "targets": 1,
                "data" : 'profile_name'
            }, {
                "targets": 2,
                "data": 'command_list',
                "render": function(data, type, row) {
                    return insert_slider(comma2br(data), 'export-row' + row['id']);
                }
            }]
        });

        $('#export-profiles-check-all').click(function () {
            toggle_check_all(export_profiles_table, this);
        });

        function toggle_check_all(data_table, this_instance) {
            var filtered_rows = data_table.$('tr', {"filter": "applied"});
            for (var i = 0; i < filtered_rows.length; i++) {
              $(filtered_rows[i]).find('.check').prop('checked', this_instance.checked);
            }
        }

        $('#export-button').on("click", function(){
            export_profiles_table.api().ajax.url("/custom_command_profiles/api/get_command_profiles").load();
            $('#export-profiles-dialog').modal({show:true, backdrop:'static'});
        });

        $('#export-profiles-done').on('click', function(e) {
            var profiles_list = [];
            $('.check').each(function(index) {
                if (this.checked) {
                    profiles_list.push($(this).val());
                }
            });
            if (profiles_list == []) {
                return false;
            }

            $('#export-profiles-form').attr('action', "{{ url_for('custom_command.export_command_profiles') }}?profiles_list[]=" + profiles_list);
            $('#export-profiles-form').submit();
        });

        $("#import-button").on("click", function() {
            $('#profile-import-dialog').modal({show:true, backdrop:'static'});
        });

        $(document).on('change', '.btn-file :file', function() {
            var input = $(this),
              numFiles = input.get(0).files ? input.get(0).files.length : 1,
              label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
            input.trigger('fileselect', [numFiles, label]);
        });

        $('.btn-file :file').on('fileselect', function(event, numFiles, label) {
            var input = $(this).parents('.input-group').find(':text'),
                log = numFiles > 1 ? numFiles + ' files selected' : label;

            if( input.length ) {
                input.val(log);
            }
        });

        $('#import-submit').on('click', function() {
            if($('.btn-file :file').val() == ''){
                bootbox.alert("Please choose a file to import.");
                return false;
            }
            $('#import-form').submit();
        });

    });
</script>

<style>
    .modal-dialog {    
        width: 850px;
    }
    .btn-file {
        position: relative;
        overflow: hidden;
    }
    .btn-file input[type=file] {
        position: absolute;
        top: 0;
        right: 0;
        min-width: 100%;
        min-height: 100%;
        font-size: 100px;
        text-align: right;
        filter: alpha(opacity=0);
        opacity: 0;
        background: red;
        cursor: inherit;
        display: block;
    }
    input[readonly] {
        background-color: white !important;
        cursor: text !important;
    }
</style>

{% endblock %}
  
{% block main %}
<!-- Main -->
<div id="export-profiles-dialog" class="modal" role="dialog">
    <div class="modal-dialog">
        <form id="export-profiles-form" name="export-profiles-form" method="post" action="">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">x</button>
                    <h4>Export Custom Command Profiles</h4>
                </div>
                <div class="modal-body">
                    <table id="export-profiles-datatable">
                        <thead>
                        <tr>
                            <th>
                                <center><input type="checkbox" id="export-profiles-check-all"></center>
                            </th>
                            <th>Profile Name</th>
                            <th>CLI Commands</th>
                        </tr>
                        </thead>
                    </table>
                    <div class="wizard-footer">
                        <div align="center">
                            <input id='export-profiles-done' data-dismiss="modal" type='submit' class='btn btn-fill btn-primary btn-wd btn-sm' name='profile-export-done' value='Export' />
                            <input type="button" id="cancel" class="btn btn-fill btn-wd btn-sm" data-dismiss="modal" value="Cancel" />
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<div id="profile-import-dialog" class="modal" role="dialog">
    <div class="modal-dialog">
        <form id="import-form" method="post" class="form-horizontal" enctype="multipart/form-data" data-msg="{{ get_flashed_messages(category_filter=['import_feedback'])[0] | nl2br }}">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">x</button>
                    <h4>Import Custom Command Profiles</h4>
                    The file to be imported must have been exported previously using the Custom Command Profile Export function.
                </div>
                <div class="modal-body">
                    <div class="form-group ">
                        <div class="col-sm-6">
                            <div class="input-group">
                                <span class="input-group-btn">
                                    <span class="btn btn-primary btn-file">
                                        Choose File<input class="form-control" type=file name=file>
                                    </span>
                                </span>
                                <input type="text" class="form-control" readonly>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="form-actions">
                        <div class="btn col-sm-offset-4">
                            <input class="btn btn-primary form-control" id="import-submit" type=submit value=Import>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-tabs" id="command-profile-tab">
                <li><a data-toggle="tab" href="#profiles-tab">Custom Command Profiles</a></li>
                <li class="dropdown">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">Create <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a data-toggle="main-tab" href="{{ url_for('custom_command.command_profile_create') }}">Custom Command Profile</a></li>
                    </ul>
                </li>
                <div class="btn-group pull-right">
                    <button id="import-button" type="button" class="btn btn-default">Import</button>
                    <button id="export-button" type="button" class="btn btn-default">Export</button>
                </div>
            </ul>
            <div class="tab-content" style="margin-top:10px;">
                <div id="profiles-tab" class="tab-pane fade in active">
                    <table class="display table" id="profile-table">
                        <thead>
                            <tr>
                                <th>Profile Name</th>
                                <th>CLI Commands</th>
                                <th>Created By</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}