csmserver/views/conformance.py
# =============================================================================
# Copyright (c) 2016, Cisco Systems, Inc
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.
# =============================================================================
from flask import Blueprint
from flask import render_template, jsonify, abort, send_file, flash
from flask_login import login_required, current_user
from flask import request, redirect, url_for

from wtforms import Form
from wtforms import StringField
from wtforms import SelectField
from wtforms import TextAreaField
from wtforms import RadioField
from wtforms import HiddenField
from wtforms import SelectMultipleField
from wtforms.validators import Length, required

from models import logger
from models import SoftwareProfile
from models import SystemOption
from models import ConformanceReport
from models import ConformanceReportEntry

from common import get_last_successful_inventory_elapsed_time
from common import get_host_active_packages
from common import get_host_inactive_packages
from common import fill_servers
from common import get_server_list
from common import get_host
from common import create_or_update_install_job
from common import fill_custom_command_profiles
from common import can_delete
from common import can_create
from common import can_install
from common import get_conformance_report_by_id
from common import get_software_profile
from common import get_software_profile_list
from common import get_software_profile_by_id
from common import delete_software_profile
from common import get_host_list_by
from common import get_hosts_by_software_profile_id
from common import get_host_software_profile_counts

from database import DBSession

from constants import UNKNOWN
from constants import HostConformanceStatus
from constants import InstallAction
from constants import JobStatus
from constants import get_temp_directory

from conformance_report import ConformanceReportWriter
from filters import get_datetime_string

from smu_info_loader import SMUInfoLoader

from forms import ServerDialogForm

from utils import is_empty
from utils import create_temp_user_directory
from utils import create_directory
from utils import make_file_writable
from utils import get_search_results

from package_utils import get_matchable_package_dict

import os
import json
import re
import datetime

conformance = Blueprint('conformance', __name__, url_prefix='/conformance')


@conformance.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if not can_install(current_user):
        abort(401)

    msg = ''
    # Software Profile import
    if request.method == 'POST':
        file = request.files['file']
        if file:
            if not allowed_file(file.filename):
                msg = "Incorrect file format -- " + file.filename + " must be .json"
            else:
                file_path = os.path.join(get_temp_directory(), "software_profiles.json")
                file.save(file_path)
                failed = ""

                with open(file_path, 'r') as f:
                    try:
                        s = json.load(f)
                    except:
                        msg = "Incorrect file format -- " + file.filename + " must be a valid JSON file."
                        flash(msg, 'import_feedback')
                        return redirect(url_for(".home"))

                    if "CSM Server:Software Profile" not in s.keys():
                        msg = file.filename + " is not in the correct Software Profile format."
                    else:
                        db_session = DBSession
                        profiles = [p for (p,) in DBSession().query(SoftwareProfile.name).all()]
                        d = s["CSM Server:Software Profile"]

                        for software_profile_name in d.keys():
                            name = ''
                            if software_profile_name in profiles:
                                name = software_profile_name
                                # Will keep appending ' - copy' until it hits a unique name
                                while name in profiles:
                                    name += " - copy"
                                msg += software_profile_name + ' -> ' + name + '\n'
                                profiles.append(name)

                            if len(name) < 100 and len(software_profile_name) < 100:
                                try:
                                    profile = SoftwareProfile(
                                        name=name if name else software_profile_name,
                                        packages=d[software_profile_name],
                                        created_by=current_user.username
                                    )
                                    db_session.add(profile)
                                    db_session.commit()
                                except:
                                    failed += software_profile_name + '\n'
                            else:
                                failed += software_profile_name + ' (name too long)\n'

                        if msg:
                            msg = "The following profiles already exist and will try to be imported under modified " \
                                  "names:\n\n" + msg + '\n'
                            if failed:
                                msg += 'The following profiles failed to import:\n\n' + failed
                        elif failed:
                            msg = 'The following profiles failed to import:\n\n' + failed
                        else:
                            msg = "Software Profile import was successful!"

                # delete file
                os.remove(file_path)

            flash(msg, 'import_feedback')
            return redirect(url_for(".home"))

    db_session = DBSession()

    conformance_form = ConformanceForm(request.form)
    assign_software_profile_to_hosts_form = AssignSoftwareProfileToHostsForm(request.form)
    view_host_software_profile_form = ViewHostSoftwareProfileForm(request.form)
    conformance_report_dialog_form = ConformanceReportDialogForm(request.form)
    make_conform_dialog_form = MakeConformDialogForm(request.form)
    batch_make_conform_dialog_form = BatchMakeConformDialogForm(request.form)

    fill_custom_command_profiles(db_session, make_conform_dialog_form.custom_command_profile.choices)
    fill_custom_command_profiles(db_session, batch_make_conform_dialog_form.batch_custom_command_profile.choices)

    export_conformance_report_form = ExportConformanceReportForm(request.form)
    export_conformance_report_form.include_host_packages.data = True
    export_conformance_report_form.exclude_conforming_hosts.data = True

    return render_template('conformance/index.html',
                           conformance_form=conformance_form,
                           assign_software_profile_to_hosts_form=assign_software_profile_to_hosts_form,
                           view_host_software_profile_form=view_host_software_profile_form,
                           conformance_report_dialog_form=conformance_report_dialog_form,
                           install_actions=[InstallAction.PRE_UPGRADE, InstallAction.INSTALL_ADD,
                                            InstallAction.INSTALL_ACTIVATE, InstallAction.POST_UPGRADE,
                                            InstallAction.INSTALL_COMMIT, InstallAction.ALL],
                           make_conform_dialog_form=make_conform_dialog_form,
                           batch_make_conform_dialog_form=batch_make_conform_dialog_form,
                           export_conformance_report_form=export_conformance_report_form,
                           server_time=datetime.datetime.utcnow(),
                           system_option=SystemOption.get(DBSession()))


@conformance.route('/software_profile/create', methods=['GET', 'POST'])
@login_required
def software_profile_create():
    if not can_create(current_user):
        abort(401)

    db_session = DBSession()

    form = SoftwareProfileForm(request.form)
    server_dialog_form = ServerDialogForm(request.form)

    fill_servers(server_dialog_form.server_dialog_server.choices, get_server_list(db_session), False)

    if request.method == 'POST' and form.validate():

        software_profile = get_software_profile(db_session, form.software_profile_name.data)

        if software_profile is not None:
            return render_template('conformance/software_profile_edit.html',
                                   form=form, system_option=SystemOption.get(db_session), duplicate_error=True)

        software_profile = SoftwareProfile(

csmserver/templates/conformance/conformance_report_dialog.html
<!--
This HTML file requires a corresponding conformance_report_dialog.js file

Caller must provide the following WTForms elements with the following IDs

    form.software_profile
-->

{% from 'host/common.html' import edit_field %}
{% from 'share/select_hosts_by_platform.html' import select_hosts_by_platform %}

{% macro conformance_report_dialog(conformance_report_dialog_form) %}

<div id="conformance-report-dialog" class="modal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal">x</button>  
                <!-- <div class="wizard-container"> -->
                <div class="card wizard-card csm-blue" id="conformance-report-dialog-wizard">
                    <form class="form-horizontal" method="post">
                        <div class="wizard-header">
                            <h3>
                                Conformance Report <br>
                            </h3>
                        </div>
                        <ul>
                            <li><a href="#dialog_software_profile" data-toggle="tab">GENERAL</a></li>
                            <li><a href="#dialog_target_hosts" data-toggle="tab">SELECT HOSTS</a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane" id="dialog_software_profile">
                                <div class="row">
                                    {{ edit_field(conformance_report_dialog_form.software_profile, label_field_width="col-sm-4", field_width="col-sm-5", class="form-control") }}
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="form-group">
                                        <label class="col-sm-4 control-label" id="label_match_criteria">Match Criteria</label>
                                        <div class=col-sm-7>
                                            {{ conformance_report_dialog_form.match_criteria }}
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="form-group ">
                                        <label class="col-sm-4 control-label" id="label_host_selection_criteria">Host Selection Criteria</label>
                                        <div class=col-sm-7>
                                            {{ conformance_report_dialog_form.host_selection_criteria }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane" id="dialog_target_hosts">
                                <div id="auto-select-hosts-panel">
                                    <h4>All hosts that match the selected Software Profile will be used for the Conformance Report.</h4>
                                </div>

                                <div id="manual-select-hosts-panel">
                                    {{ select_hosts_by_platform(conformance_report_dialog_form.platform, conformance_report_dialog_form.software, conformance_report_dialog_form.region, conformance_report_dialog_form.role) }}
                                </div>
                            </div>
                        </div>
                        <div class="wizard-footer">
                            <div class="pull-right">
                                <input type='button' class='btn btn-next btn-fill btn-primary btn-wd btn-sm' name='next' value='Next' />
                                <input id='on-conformance-report-dialog-submit' data-dismiss="modal" type='button' class='btn btn-finish btn-fill btn-primary btn-wd btn-sm' name='finish' value='Finish' />
                            </div>
                            <div class="pull-left">
                                <input type='button' class='btn btn-previous btn-fill btn-default btn-wd btn-sm' name='previous' value='Previous' />
                            </div>
                            <div class="clearfix"></div>
                        </div>
                    </form>
                </div>
                <!-- wizard container -->
            </div>
        </div>
    </div>
</div>

{% endmacro %}

csmserver/templates/conformance/profile_edit.html
{% extends 'base_software.html' %}

{% from 'host/common.html' import edit_field %}
{% from 'host/common.html' import alert_duplicate %}
{% from 'share/server_software_dialog.html' import server_software_dialog %}
{% from 'share/cisco_software_dialog.html' import cisco_software_dialog %}

{% if request.endpoint.endswith('edit') %}
    {% set isEdit = True %}
{% else %}
    {% set isEdit = False %}
{% endif %}

{% block head %}

<script src="/static/jquery/js/smu_info_dialog.js"></script>
<script src="/static/jquery/js/validate_software.js"></script>
<script src="/static/jquery/js/server_software_dialog.js"></script>
<script src="/static/jquery/js/cisco_software_dialog.js"></script>

<script>
    $(function() {
        var spinner = $('#spinner');
        spinner.hide();

        $('#form').submit(function() {
            var current_form = this;
            var profile_name = $('#profile_name').val();
            var acceptable_string = get_acceptable_string(profile_name);
            $('#software_packages').val(trim_lines($('#software_packages').val()));

            if (acceptable_string != profile_name) {
                var message = get_acceptable_string_message('Profile name', profile_name, acceptable_string);
                bootbox.confirm(message, function(result) {
                    if (result) {
                        $('#profile_name').val(acceptable_string);
                    }
                });
            } else {
                return true;
            }

            return false;
        });

        $('#browse-cisco-button').on('click', function(e) {
            display_cisco_software_dialog([]);
        });

        $('#on-cisco-software-dialog-submit').click(function(e) {
            var new_software_packages = [];

            $('.check').each(function(index) {
                if (this.checked) {
                    $(this).attr('checked', false);
                    new_software_packages.push($(this).val());
                }
            });
            update_software_packages(new_software_packages);
        });

        function update_software_packages(new_software_packages) {
            if (new_software_packages.length == 0) {
                return;
            }

            var software_packages = convert_lines_to_list($('#software_packages').val());

            if (software_packages.length > 0) {
                bootbox.dialog({
                    message: "Overwrite existing selected software packages?  Click 'Yes' to overwrite or 'No' to append.",
                    title: "Confirmation",
                    buttons: {
                        success: {
                            label: "Yes",
                            className: "btn-primary",
                            callback: function() {
                                $('#software_packages').val(String(new_software_packages).replace(/,/g, '\n'));
                            }
                        },
                        danger: {
                            label: "No",
                            className: "btn-default",
                            callback: function() {
                                for (i = 0; i < new_software_packages.length; i++) {
                                    software_packages.push(new_software_packages[i]);
                                }
                                $('#software_packages').val(String(software_packages).replace(/,/g, '\n'));
                            }
                        },
                    }
                });
            } else {
                $('#software_packages').val(String(new_software_packages).replace(/,/g, '\n'));
            }
        }

        $('#validate-software').click(function(e) {
            validate_software_packages();
        });

        function validate_software_packages() {
            validate_software($('#software_packages'), $('#software_packages'), spinner);
        }
        
        $('#browse-server-button').on('click', function(e) {                  
            display_server_software_dialog(-1, '', '');
        });
        
        $('#on-server-software-dialog-submit').click(function(e) {
            update_software_packages(server_software_selector.get_selected_items());
        });

    });
</script>
  
<style>
    .modal-dialog {    
        width: 850px;
    }
    a:link, a:visited {
        text-decoration:none;
    }
    th,
    td {
        white-space: nowrap;
    }
</style>
  
{% endblock %}

{% block main %}

{{ cisco_software_dialog(system_option.enable_cco_lookup) }}
{{ server_software_dialog(server_dialog_form.server_dialog_server, server_dialog_form.server_dialog_server_directory, server_dialog_form.server_dialog_target_software) }}
 
<div class="row">
    <div class="well col-sm-offset-2 col-sm-8">
        <form id="form" method=post class="form-horizontal">
            <legend>{% if isEdit %}Edit Software Profile{% else %}Create Software Profile{% endif %}</legend>
            
            {{ alert_duplicate(form.profile_name.data, duplicate_error) }}
            {{ edit_field(form.profile_name, class="form-control") }}
            
            <div class="form-group ">
                <label class="col-sm-4 control-label">Select From</label>  
                <div class=col-sm-8>    
                    <span id="add-widget-panel">
                    <a id="browse-server-button" href="javascript://">
                        <img src="/static/browse_server.png">&nbsp;Server Repository&nbsp;&nbsp;&nbsp;
                    </a>
                    <a id="browse-cisco-button" href="javascript://">
                        <img src="/static/internet.png">&nbsp;CCO&nbsp;&nbsp;&nbsp;
                    </a>  
                    </span> 
                </div>
            </div>
            
            {{ edit_field(form.software_packages, class="form-control", spellcheck="false", rows="10") }}
            
            <div class="form-actions">
                <div class="btn col-sm-offset-5">
                    <button id="validate-software" type="button" class="btn btn-default">Validate</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="button" onClick="location.href='{{ url_for('conformance.home') }}'" class="btn btn-default">Cancel</button>
                    <img id="spinner" src="{{ url_for('static', filename='spinner.gif') }}">
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

csmserver/templates/conformance/software_profile_edit.html
{% extends 'base_software.html' %}

{% from 'host/common.html' import edit_field %}
{% from 'host/common.html' import alert_duplicate %}
{% from 'share/server_software_dialog.html' import server_software_dialog %}
{% from 'share/cisco_software_dialog.html' import cisco_software_dialog %}

{% if request.endpoint.endswith('edit') %}
    {% set isEdit = True %}
{% else %}
    {% set isEdit = False %}
{% endif %}

{% block head %}

<script src="/static/jquery/js/smu_info_dialog.js"></script>
<script src="/static/jquery/js/server_software_dialog.js"></script>
<script src="/static/jquery/js/cisco_software_dialog.js"></script>

<script>
    $(function() {
        var spinner = $('#spinner');
        spinner.hide();

        $('#form').submit(function() {
            var current_form = this;
            var software_profile_name = $('#software_profile_name').val();
            var acceptable_string = get_acceptable_string(software_profile_name);
            $('#software_packages').val(trim_lines($('#software_packages').val()));

            if (acceptable_string != software_profile_name) {
                var message = get_acceptable_string_message('Software Profile name', software_profile_name, acceptable_string);
                bootbox.confirm(message, function(result) {
                    if (result) {
                        $('#software_profile_name').val(acceptable_string);
                    }
                });
            } else {
                return true;
            }

            return false;
        });

        $('#browse-cisco-button').on('click', function(e) {
            display_cisco_software_dialog([]);
        });

        $('#on-cisco-software-dialog-submit').click(function(e) {
            var new_software_packages = [];

            $('.check').each(function(index) {
                if (this.checked) {
                    $(this).attr('checked', false);
                    new_software_packages.push($(this).val());
                }
            });
            update_software_packages(new_software_packages);
        });

        function update_software_packages(new_software_packages) {
            if (new_software_packages.length == 0) {
                return;
            }

            var software_packages = convert_lines_to_list($('#software_packages').val());

            if (software_packages.length > 0) {
                bootbox.dialog({
                    message: "Overwrite existing selected software packages?  Click 'Yes' to overwrite or 'No' to append.",
                    title: "Confirmation",
                    buttons: {
                        success: {
                            label: "Yes",
                            className: "btn-primary",
                            callback: function() {
                                $('#software_packages').val(String(new_software_packages).replace(/,/g, '\n'));
                            }
                        },
                        danger: {
                            label: "No",
                            className: "btn-default",
                            callback: function() {
                                for (i = 0; i < new_software_packages.length; i++) {
                                    software_packages.push(new_software_packages[i]);
                                }
                                $('#software_packages').val(String(software_packages).replace(/,/g, '\n'));
                            }
                        },
                    }
                });
            } else {
                $('#software_packages').val(String(new_software_packages).replace(/,/g, '\n'));
            }
        }

        $('#optimize-software').click(function(e) {
            optimize_software_packages();
        });

        function optimize_software_packages() {
            optimize_software($('#software_packages'), $('#software_packages'), spinner);
        }
        
        $('#browse-server-button').on('click', function(e) {                  
            display_server_software_dialog(-1, '', '');
        });
        
        $('#on-server-software-dialog-submit').click(function(e) {
            update_software_packages(server_software_selector.get_selected_items());
        });

    });
</script>
  
<style>
    .modal-dialog {    
        width: 850px;
    }
    a:link, a:visited {
        text-decoration:none;
    }
    th,
    td {
        white-space: nowrap;
    }
</style>
  
{% endblock %}

{% block main %}

{% include 'share/optimize_software_dialog.html' %}
{{ cisco_software_dialog(system_option.enable_cco_lookup) }}
{{ server_software_dialog(server_dialog_form.server_dialog_server, server_dialog_form.server_dialog_server_directory, server_dialog_form.server_dialog_target_software) }}
 
<div class="row">
    <div class="well col-sm-offset-2 col-sm-8">
        <form id="form" method=post class="form-horizontal">
            <legend>{% if isEdit %}Edit Software Profile{% else %}Create Software Profile{% endif %}</legend>
            
            {{ alert_duplicate(form.software_profile_name.data, duplicate_error) }}
            {{ edit_field(form.software_profile_name, class="form-control") }}
            
            <div class="form-group ">
                <label class="col-sm-4 control-label">Select From</label>  
                <div class=col-sm-8>    
                    <span id="add-widget-panel">
                    <a id="browse-server-button" href="javascript://">
                        <img src="/static/browse_server.png">&nbsp;Server Repository&nbsp;&nbsp;&nbsp;
                    </a>
                    <a id="browse-cisco-button" href="javascript://">
                        <img src="/static/internet.png">&nbsp;CCO&nbsp;&nbsp;&nbsp;
                    </a>  
                    </span> 
                </div>
            </div>
            
            {{ edit_field(form.software_packages, class="form-control", wrap="off", style="overflow:scroll;resize: none", spellcheck="false", rows="10") }}
            
            <div class="form-actions">
                <div class="btn col-sm-offset-5">
                    <button id="optimize-software" type="button" class="btn btn-default">Optimize</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="button" onClick="location.href='{{ url_for('conformance.home') }}'" class="btn btn-default">Cancel</button>
                    <img id="spinner" src="{{ url_for('static', filename='spinner.gif') }}">
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}