csmserver/views/tools.py
# =============================================================================
# Copyright (c) 2016, Cisco Systems, Inc
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGE.
# =============================================================================
from flask import Blueprint
from flask import abort
from flask import jsonify, render_template, request
from flask_login import login_required, current_user

from database import DBSession

from models import logger
from models import CreateTarJob

from common import get_jump_host_list

from wtforms import Form
from wtforms import StringField
from wtforms.validators import Length, required

from utils import get_tarfile_file_list, get_file_list, untar, make_file_writable

from constants import get_repository_directory, get_temp_directory
from constants import JobStatus

from package_utils import is_external_file_a_smu
from package_utils import is_external_file_a_release_software

import os

tools = Blueprint('tools', __name__, url_prefix='/tools')


@tools.route('/hosts/')
@login_required
def host_list():
    return render_template('host/index.html')


@tools.route('/jump_hosts/')
@login_required
def jump_host_list():
    db_session = DBSession()

    hosts = get_jump_host_list(db_session)
    if hosts is None:
        abort(404)

    return render_template('jump_host/index.html', hosts=hosts)


@tools.route('/create_tar_file')
@login_required
def create_tar_file():
    create_tar_form = CreateTarForm(request.form)
    return render_template('tools/create_tar_file.html', form=create_tar_form)


@tools.route('/api/create_tar_job', methods=["POST"])
@login_required
def api_create_tar_job():
    db_session = DBSession()

    json_data = request.get_json()
    server_id = json_data['server_id']
    server_directory = json_data['server_directory']
    source_tars = json_data['source_tars']
    contents = json_data['tar_contents']
    additional_packages = json_data['additional_packages']
    new_tar_name = json_data['new_tar_name']

    create_tar_job = CreateTarJob(
        server_id=server_id,
        server_directory=server_directory,
        source_tars=','.join(source_tars),
        contents=','.join(contents),
        additional_packages=','.join(additional_packages),
        new_tar_name=new_tar_name,
        created_by=current_user.username,
        status_message='Job Submitted.',
        status=JobStatus.SCHEDULED)

    db_session.add(create_tar_job)
    db_session.commit()

    job_id = create_tar_job.id

    return jsonify({'status': 'OK', 'job_id': job_id})


@tools.route('/api/get_progress')
@login_required
def get_progress():
    db_session = DBSession()
    job_id = request.args.get('job_id')

    tar_job = db_session.query(CreateTarJob).filter(CreateTarJob.id == job_id).first()
    if tar_job is None:
        logger.error('Unable to retrieve Create Tar Job: %s' % job_id)
        return jsonify(status='Unable to retrieve job')

    return jsonify(status='OK', progress=tar_job.status_message)


@tools.route('/api/get_tar_contents')
@login_required
def get_tar_contents():
    files = request.args.getlist('files[]')
    files = files[0].strip().split(',')
    rows = []
    repo_path = get_repository_directory()

    for file in files:
        if file:
            for f in get_tarfile_file_list(repo_path + file):
                row = {}
                row['file'] = repo_path + file + '/' + f
                row['filename'] = f
                row['source_tar'] = file
                rows.append(row)
    return jsonify(**{'data': rows})


@tools.route('/api/get_full_software_tar_files_from_csm_repository/')
@login_required
def get_full_software_tar_files_from_csm_repository():
    rows = []
    file_list = get_file_list(get_repository_directory())

    for filename in file_list:
        if is_external_file_a_release_software(filename):
            statinfo = os.stat(get_repository_directory() + filename)
            row = {}
            row['image_name'] = filename
            row['image_size'] = '{} bytes'.format(statinfo.st_size)
            rows.append(row)

    return jsonify(**{'data': rows})


@tools.route('/api/get_sp_files_from_csm_repository/')
@login_required
def get_sp_files_from_csm_repository():
    rows = []
    file_list = get_file_list(get_repository_directory())

    for filename in file_list:
        if is_external_file_a_smu(filename):
            statinfo = os.stat(get_repository_directory() + filename)
            row = {}
            row['image_name'] = filename
            row['image_size'] = '{} bytes'.format(statinfo.st_size)
            rows.append(row)

    return jsonify(**{'data': rows})


class CreateTarForm(Form):
    new_tar_name = StringField('New Tar File Name', [required(), Length(max=30)])

csmserver/templates/jump_host/edit.html
{% extends 'base_software.html' %}

{% from 'host/common.html' import edit_field %}
{% from 'host/common.html' import alert_duplicate %}

{% if request.endpoint.endswith('edit') %}
    {% set isEdit = True %}
{% else %}
    {% set isEdit = False %}
{% endif %}

{% block head %}
<script>
    $(function() {
        var spinner = $('#spinner');
        spinner.hide();

        {% if isEdit %}
        var is_password_panel_visible = false;
        var password_panel = $('#password-panel');

        {% if form.password_placeholder != "No Password Specified" %}
            password_panel.hide();
        {% endif %}

        $('#modify-password').on("click", function() {
            if (is_password_panel_visible) {
                password_panel.hide();
                is_password_panel_visible = false;
            } else {
                password_panel.show();
                is_password_panel_visible = true;
            }
        });

        $('#remove-password').on("click", function() {
            var message = "This operation will remove the jump server password on file.  Proceed?";
            bootbox.confirm(message, function(result) {
                if (result) {
                    $.ajax({
                        "url": "{{ url_for('home.api_remove_jump_host_password', hostname=form.hostname.data) }}",
                        type: "DELETE",
                        success: function(response) {
                            if (response.status == 'OK') {
                                bootbox.alert("Password has been removed.");
                                $('#password').attr("placeholder", "No Password Specified.");
                            } else {
                                bootbox.alert("Unable to remove password.");
                            }
                        }
                    });
                }
            });
        });
        {% endif %}

        $('#password').password();

        $('#verify-reachability').on("click", function() {
            spinner.show();

            var formData = {
                hostname: '{{ form.hostname.data }}',
                host_or_ip: $('#host_or_ip').val(),
                username: $('#username').val(),
                password: $('#password').val(),
                connection_type: $('#connection_type').val(),
                port_number: $('#port_number').val()
            };

            $.ajax({
                url: "/home/api/check_jump_host_reachability",
                dataType: 'json',
                data: formData,
                success: function(response) {
                    if (response.status == 'OK') {
                        display_success();
                    } else {
                        display_error();
                    }
                },
                error: function(XMLHttpRequest, textStatus, errorThrown) {
                    display_error();
                }
            });
        });

        function display_success() {
            spinner.hide();
            //bootbox.alert("This function has not been implemented.");
            $('#verify-reachability').removeClass("btn-danger");
            $('#verify-reachability').addClass("btn-primary");
            bootbox.alert("<img src=\"{{ url_for('static', filename='green_check.png') }}\">CSM Server is able to reach the specified host.  However, unlike managed host reachability test, this test does not verify username and password authentication.");
        }

        function display_error() {
            spinner.hide();
            $('#verify-reachability').removeClass("btn-primary");
            $('#verify-reachability').addClass("btn-danger");
            bootbox.alert("<img src=\"{{ url_for('static', filename='error.png') }}\">Unable to reach the specified host or you are not an authorized user.");
        }

        $('#form').submit(function() {

            var hostname = $('#hostname').val();
            var acceptable_string = get_acceptable_string(hostname);

            if (acceptable_string != hostname) {
                var message = get_acceptable_string_message('Jump server name', hostname, acceptable_string);
                bootbox.confirm(message, function(result) {
                    if (result) {
                        $('#hostname').val(acceptable_string);
                    }
                });
            } else {
                return true;
            }

            return false;
        });

    });
</script>
{% endblock %}

{% block main %}
<div class="row">
    <div class="well col-sm-offset-2 col-sm-8">
        <form id="form" method="post" class="form-horizontal">
            <legend>{% if isEdit %}Edit Jump Server{% else %}Create Jump Server{% endif %}</legend>

            {{ alert_duplicate(form.hostname.data, duplicate_error) }}
            {{ edit_field(form.hostname, maxlength=30, field_width="col-sm-4", class="form-control",
                placeholder="Unique Name on CSM Server") }}

            <legend>Connection Parameters</legend>
            {{ edit_field(form.connection_type, field_width="col-sm-4", class="form-control") }}
            {{ edit_field(form.host_or_ip, maxlength=30, field_width="col-sm-4", class="form-control",
                placeholder="Server or IP") }}

            {{ edit_field(form.port_number, field_width="col-sm-4", class="form-control",
                placeholder="Leave Blank for Default") }}

            {% if isEdit %}
                {% set extra_field ='<a href="javascript://" id="modify-password">
                    <img src=\"/static/lock.png\" title="Show/Hide Password Field"></a>' %}
                {{ edit_field(form.username, autocomplete="off", field_width="col-sm-4", maxlength=100, class="form-control", extra_field=extra_field ) }}
            {% else %}
                {{ edit_field(form.username, autocomplete="off", field_width="col-sm-4", maxlength=100, class="form-control") }}
            {% endif %}
            <div id="password-panel">
                {% if isEdit %}
                    {% set extra_field ='<a href="javascript://" id="remove-password">
                        <img src=\"/static/remove.png\" title="Click to Remove Password on File"></a>' %}

                    {{ edit_field(form.password, autocomplete="off", field_width="col-sm-4", maxlength=100, class="form-control", extra_field=extra_field,
                        placeholder=form.password_placeholder) }}
                {% else %}
                    {{ edit_field(form.password, autocomplete="off", field_width="col-sm-4", maxlength=100, class="form-control") }}
                {% endif %}
            </div>
            <div class="form-actions">
                <div class="btn col-sm-offset-4">
                    <button id="verify-reachability" type="button" class="btn btn-danger">Check Reachability</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="button" onClick="history.back(1);" class="btn btn-default">Cancel</button>
                    <img id="spinner" src="{{ url_for('static', filename='spinner.gif') }}">
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

csmserver/templates/jump_host/index.html
{% extends 'base_software.html' %}

{% block title %}<center><h4><b>Jump Servers</b></h4></center>{% endblock %}

{% block head %}
<script>
    $(function() {
        $("#datatable").dataTable();

        $(".host-delete-link").on("click", function() {
            var delete_url = $(this).attr('data-delete-url');
            var delete_host = $(this).attr('delete-host');

            bootbox.confirm("You are about to delete jump host \'" + delete_host + "\'.  OK to proceed?", function(result) {
                if (result) {
                    $.ajax({
                        url: delete_url,
                        type: 'DELETE',
                        success: function(result) {
                            if (result.status == 'OK') {
                                window.location = "{{ url_for('tools.jump_host_list') }}";
                            } else {
                                bootbox.alert('Delete failed.');
                            }
                        }
                    });
                }
            });
        });
    });
</script>
{% endblock %}

{% block main %}
<div class="container" style="margin-top: 10px">
    <table cellspacing="0" class="display table" id="datatable">
        <thead>
            <tr>
                <th>Jump Server</th>
                <th>Connection</th>
                <th>Name or IP</th>
                <th>Port</th>
                <th>Username</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for host in hosts %}
                <tr>
                    <td><a href="{{ url_for('jump_host_edit', hostname = host.hostname) }}">{{ host.hostname }}</a></td>
                    <td>{{ host.connection_type }}
                    <td>{{ host.host_or_ip }}</td>

                    {% if host.port_number %}
                        <td>{{ host.port_number }}</td>
                    {% else %}
                        <td>Default</td>
                    {% endif %}

                    <td>{{ host.username }}</td>
                    <td><a class="host-delete-link" href="javascript://"
                        delete-host="{{ host.hostname }}"
                        data-delete-url="{{ url_for('jump_host_delete', hostname = host.hostname) }}">Delete</a></td>
                </tr>
            {% else %}
                <h3>No Jump Server</h3>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}